version: "3.9"

services:
  spring-boot:
    image: thecheesytimes-backend:latest
    container_name: spring-boot
    restart: unless-stopped
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host